### ISSUE TITLE
modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/5.4.0-67-generic

### ISSUE THREAD

**Issue by scottprovost** [TaPO4eg3D/discord-monitors-to-vc#13]
modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/5.4.0-67-generic

**Comment by MrNinso** [comment]
you need install v4l2loopback first.

for ubuntu:
``
sudo apt install v4l2loopback-dkms
``

for fedora/centos:
``
 sudo yum install v4l2loopback
``

if you need more information this is the v4l2loopback repo: https://github.com/umlaeute/v4l2loopback

**Comment by TaPO4eg3D** [comment]
@MrNinso Thanks for covering it! I think it can be closed now

**Comment by Gormezoglu** [comment]
> you need install v4l2loopback first.
> 
> for ubuntu: `sudo apt install v4l2loopback-dkms`
> 
> for fedora/centos: `sudo yum install v4l2loopback`
> 
> if you need more information this is the v4l2loopback repo: https://github.com/umlaeute/v4l2loopback

I have installed loopback but nothing changed. Is there any other way ?

**Comment by TaPO4eg3D** [comment]
I suggest using Discord with system Electron. That way there will be no issues with screen sharing
https://aur.archlinux.org/packages/discord-canary-electron-bin/

**Comment by xxxtrashcion** [comment]
> > you need install v4l2loopback first.
> > for ubuntu: `sudo apt install v4l2loopback-dkms`
> > for fedora/centos: `sudo yum install v4l2loopback`
> > if you need more information this is the v4l2loopback repo: https://github.com/umlaeute/v4l2loopback
> 
> I have installed loopback but nothing changed. Is there any other way ?

You ever find a solution?

**Comment by TaPO4eg3D** [comment]
@xxxtrashcion Try to use this project if you're having troubles with the standart Discord app: https://github.com/Vencord/Vesktop
