### ISSUE TITLE
Mirrored

### ISSUE THREAD

**Issue by Sebiann** [TaPO4eg3D/discord-monitors-to-vc#3]
So by me it just mirrors my Content, any fix or am i just stupid
![image](https://user-images.githubusercontent.com/32842507/57966607-bb69d600-7954-11e9-80b9-ea5031ec5352.png)

**Comment by TaPO4eg3D** [comment]
It's ok that you see a mirrored image because Discord treats your screen as a webcam. Your interlocutor will see your screen in the way it should be

**Comment by Sebiann** [comment]
oh ok, thank you for the infos
