### ISSUE TITLE
Doesn't work with 2560x1440

### ISSUE THREAD

**Issue by kattjevfel** [TaPO4eg3D/discord-monitors-to-vc#4]
When using on a resolution of 2560x1440 output will either show nothing, or a corrupted image of what was shown prior to changing resolution. It is however properly detected in the list as the right resolution.
```
* Select a monitor you want to share
====================================

Monitor currently emulating: 0: +*DP-4 2560/597x1440/336+2560+0  DP-4

> 0: +*DP-4 2560/597x1440/336+2560+0  DP-4
  1: +DP-0 2560/597x1440/336+0+0  DP-0
```

![black](https://too.lewd.se/867d1f1203b0_2019-05-19_12-47-35.webp)
![garbage](https://too.lewd.se/596e0b77ce41_2019-05-19_12-36-10.webp)

Lowering FPS does not help.

**Comment by TaPO4eg3D** [comment]
It's hard to figure out a problem because I don't have a monitor with that resolution, and the script consists out of two programs cooperating. The actual problem can be either in ffmpeg or in v4l2loopback, or maybe in both.

Nevertheless, I'll do my best in investigating this problem.

**Comment by botiapa** [comment]
It doesn't work with 2560\*1080 or 1680\*1050 either. I think something is wrong with v4l2loopback. I'll try to look into it.

**Comment by kattjevfel** [comment]
> It doesn't work with 2560*1080 or 1680*1050 either. I think something is wrong with v4l2loopback. I'll try to look into it.

I've fixed the issue in this fork over here: https://github.com/ShayBox/Mon2Cam

**Comment by botiapa** [comment]
This can be closed as we fixed everything in the fork.
