### ISSUE TITLE
Discord shows monitor mirrored

### ISSUE THREAD

**Issue by Tsubajashi** [TaPO4eg3D/discord-monitors-to-vc#7]
Discord shows the camera mirrored.
![Screenshot_20190824_180513](https://user-images.githubusercontent.com/21346945/63638522-a1453f80-c689-11e9-87c9-9ac7311f75b1.png)

Manjaro KDE, 1080p + 768p Monitor

**Comment by TaPO4eg3D** [comment]
Duplicate of https://github.com/TaPO4eg3D/discord-monitors-to-vc/issues/3
