### ISSUE TITLE
Cannot get to run in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by TogarUshindi** [TaPO4eg3D/discord-monitors-to-vc#8]
I'm on Ubuntu 18.04 running Gnome and having several problems running this. Not sure whether to post about the issues here or via Github.

Running the release, executing with `./discord-monitors-to-vc` , returns with an error:

`[31056] Error loading Python lib '/tmp/_MEIsfAKGG/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version \GLIBC_2.28' not found (required by /tmp/_MEIsfAKGG/libpython3.7m.so.1.0)`

...

So next, I attempted running from source. I noticed that the current release on the GitHub rep "release" tab is marked "stable" and says it has "5 commits to master since this release." It does not contain "requirements.txt" as is needed to run.

So, I downloaded the "master" .zip through "Clone or Download" option.

Once downloaded, first I checked for my needed dependencies. I already have ffmpeg, so next installed v4l2loopback:

`sudo apt-get install v4l2loopback-dkms`

Then I installed pip 9.0.1:

`sudo apt install python-pip`

Then ran `pip install -r requirements.txt` as instructed on the GitHub rep.

I then ran the program through `python main.py` and it returned with the following error:

`Traceback (most recent call last):File "`[`main.py`](https://main.py)`", line 175, in <module>`[`subprocess.run`](https://subprocess.run)`('sudo modprobe v4l2loopback video_nr=4 \'card_label=VirtualScreen\'', shell=True)AttributeError: 'module' object has no attribute 'run'`

When that failed, I tried running `script.sh` by double-clicking the icon in gnome. It opens a Terminal window. After inputting my password, the script runs, but when I select which monitor I want to use, the terminal window closes.

...

So next, I tried manually opening a terminal window and ran `./script.sh` and it runs; I select my monitor, but then this happens:

`Monitors: 2`

`0: +*DVI-I-2 1920/518x1200/324+1920+0 DVI-I-2`

`1: +DVI-I-3 1920/518x1200/324+0+0 DVI-I-3`

`Which monitor you want to share: 0`

`ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers`

`built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)`

`configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared`

`libavutil 55. 78.100 / 55. 78.100`

`libavcodec 57.107.100 / 57.107.100`

`libavformat 57. 83.100 / 57. 83.100`

`libavdevice 57. 10.100 / 57. 10.100`

`libavfilter 6.107.100 / 6.107.100`

`libavresample 3. 7. 0 / 3. 7. 0`

`libswscale 4. 8.100 / 4. 8.100`

`libswresample 2. 9.100 / 2. 9.100`

`libpostproc 54. 7.100 / 54. 7.100`

`[x11grab @ 0x558c54630780] Stream #0: not enough frames to estimate rate; consider increasing probesize`

`Input #0, x11grab, from ':1+1920,0':`

`Duration: N/A, start: 1570148834.943565, bitrate: N/A`

`Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1200, 60 fps, 1000k tbr, 1000k tbn, 1000k tbc`

`Stream mapping:Stream #0:0 -> #0:0 (rawvideo (native) -> rawvideo (native))`

`Press [q] to stop, [?] for help`

`[v4l2 @ 0x558c5463a500] ioctl(VIDIOC_G_FMT): Invalid argument`

`Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument`

`Error initializing output stream 0:0 --`

`Conversion failed!`

**Comment by botiapa** [comment]
I had this problem as well. Firstly check if v4l2loopback is actually loaded (google it) and use this fork: https://github.com/ShayBox/Mon2Cam I don't have time now, but tell me if you could get it working, I can help you later if you still need it.

**Comment by TogarUshindi** [comment]
Hey, thanks for replying. I actually did move to the fork, and not sure if I'm implementing it correctly. The Test video screen is black, and when selecting the application window to share video with, still ignores everything and shares both screens. At least I'm not having the problem I was before, but it still does not work.

**Comment by botiapa** [comment]
Could you provide me the command that you use when you run it, and your monitor resolution?

**Comment by TogarUshindi** [comment]
I just followed the instructions on the fork:

```
user@host:~/apps/Mon2Cam/Mon2Cam-master$ ./Mon2Cam.sh
Monitors: 2
 0: +*DVI-I-2 1920/518x1200/324+1920+0  DVI-I-2
 1: +DVI-I-3 1920/518x1200/324+0+0  DVI-I-3
Which monitor: 0
[sudo] password for user: 
CTRL + C to stop
Your screen will look mirrored for you, not others
user@host:~/apps/Mon2Cam/Mon2Cam-master$ 
```

**Comment by botiapa** [comment]
I'm not in front of a linux OS atm but try this:
`./Mon2Cam.sh -r 1920:1080 -b`

This will set the output resolution to _1920x1080_ and add black bars to avoid stretching the image

**Comment by TogarUshindi** [comment]
![Screenshot from 2019-10-16 09-49-03](https://user-images.githubusercontent.com/54905590/66940716-47faec00-effa-11e9-8199-b03cecc5b15f.png)

Preview still appears black. I won't have anyone to test an actual video call with until later tonight, but my guess is it will still not recognize specific application windows during source selection.

**Comment by botiapa** [comment]
The previev shows exactly what the other person will see so yeah.

**Comment by botiapa** [comment]
I'll try to think about this later.

**Comment by botiapa** [comment]
The problem is probably the resolution of your monitor. But this should've fixed that.

**Comment by TogarUshindi** [comment]
Well, if anything, I appreciate the hard work and strife my situation is causing you, regardless of it benefiting someone you've never met. :)

**Comment by botiapa** [comment]
Yeah, no problem at all. I had the same issues as you and it was very frustrating, so I understand your situation if you know that I mean.

So could you run a ffplay /dev/video50 command and send me the first couple of lines it outputs (information about the source like resolution and fps), and maybe a screenshot as well just to see if the borders work.
You should run this command while Mon2Cam is running of course.

**Comment by TogarUshindi** [comment]
Yeah, actually just to see what would happen, I ran it before and after I executed Mon2Cam. Here's before:

```
ffplay version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2003-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[video4linux2,v4l2 @ 0x7fdf94000b80] ioctl(VIDIOC_G_FMT): Invalid argument
/dev/video50: Invalid argument
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   
```

Here's after:

```
ffplay version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2003-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[video4linux2,v4l2 @ 0x7fdf94000b80] ioctl(VIDIOC_G_FMT): Invalid argument
/dev/video50: Invalid argument
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   
```

They look identical to me...

That "invalid argument" thing looks suspicious.

**Comment by botiapa** [comment]
Judging by this log either v4l2loopback fails to create the video source, or ffmpeg fails to write to it. When you run ./Mon2Cam.sh does it exit immediately or does it wait for "CTRL+C"? Because if it exits, then an error occured silently.

Could you post the outputs of these commands?

sudo modprobe v4l2loopback video_nr=50 'card_label=Mon2Cam'
ls /dev/ | grep video

The first should create the video source, and the last one outputs all sources that can be found

**Comment by TogarUshindi** [comment]
Exits back to the prompt right after selecting which monitor, yeah. I thought that was funny, too.

Output of the command(s) is absolutely nothing; goes back to prompt.

Edit: Actually, wait, sorry, hold up. The second line didn't copy/paste.

Output:

`video50`

**Comment by botiapa** [comment]
Okay then v4l2loopback works. Then something is wrong with ffmpeg.

Please remove `&> /dev/null` from the end of the script. This'll enable debugging so we can see the output of ffmpeg (why it's failing)

**Comment by TogarUshindi** [comment]
```
Monitors: 2
 0: +*DVI-I-2 1920/518x1200/324+1920+0  DVI-I-2
 1: +DVI-I-3 1920/518x1200/324+0+0  DVI-I-3
Which monitor: 0
CTRL + C to stop
Your screen will look mirrored for you, not others
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[x11grab @ 0x55df90f3a780] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, x11grab, from ':1+1920,0':
  Duration: N/A, start: 1571330840.250214, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1200, 60 fps, 1000k tbr, 1000k tbn, 1000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> rawvideo (native))
Press [q] to stop, [?] for help
[v4l2 @ 0x55df90f44500] ioctl(VIDIOC_G_FMT): Invalid argument
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 
Conversion failed!

```

**Comment by botiapa** [comment]
Interesting error I have no idea what it refers to. But someone else had the same problem here: https://askubuntu.com/questions/881305/is-there-any-way-ffmpeg-send-video-to-dev-video0-on-ubuntu

Could you open this issue on the fork as well? Maybe @ShayBox has an idea
You might also try to reinstall v4l2 with information from the provided link (you might even try to compile it yourself)

**Comment by TogarUshindi** [comment]
Sure thing! Can I just refer to this thread instead of having to write out everything?

**Comment by botiapa** [comment]
Yeah, probably.

**Comment by botiapa** [comment]
This issue is solved, especially now that he uses Mon2Cam.
