### ISSUE TITLE
Running the program: AttributeError: `module` object has no attribute `run` (main.py, line 175)

### ISSUE THREAD

**Issue by markspl** [TaPO4eg3D/discord-monitors-to-vc#9]
If I run the program with the command listed on `README.md` I get an error:

    $ python main.py 
    Traceback (most recent call last):
        File "main.py", line 175, in <module>
        subprocess.run('sudo modprobe v4l2loopback video_nr=4 \'card_label=VirtualScreen\'', shell=True)
    AttributeError: 'module' object has no attribute 'run'

But if I run a command `./script.sh` (which I tried for just testing) it actually runs the program succesfully (meaning no errors appeared while trying this out):

    $ ./script.sh 
    Monitors: 2
    0: +*HDMI-0 1920/598x1080/336+0+0  HDMI-0
    1: +DVI-0 1680/474x1050/296+1920+30  DVI-0
    Which monitor you want to share:

With command `./script.sh` program runs, but Discord couldn't notice any differences. Tried the program before starting and while screenshare was on.

I've installed using command `pip install ...` which completed succesfully. Here's log when I try run it again:

    $ pip install -r requirements.txt 
    Requirement already satisfied: asciimatics==1.11.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (1.11.0)
    Requirement already satisfied: future in /usr/local/lib/python2.7/dist-packages (from asciimatics==1.11.0->-r requirements.txt (line 1)) (0.18.0)
    Requirement already satisfied: Pillow>=2.7.0 in /usr/local/lib/python2.7/dist-packages (from asciimatics==1.11.0->-r requirements.txt (line 1)) (6.2.0)
    Requirement already satisfied: pyfiglet>=0.7.2 in /usr/local/lib/python2.7/dist-packages (from asciimatics==1.11.0->-r requirements.txt (line 1)) (0.8.post1)
    Requirement already satisfied: wcwidth in /usr/local/lib/python2.7/dist-packages (from asciimatics==1.11.0->-r requirements.txt (line 1)) (0.1.7)

**Comment by TaPO4eg3D** [comment]
Have you tried to use the version from the "Release" tab?
I don't have two monitors now and have no time to maintain this project, so I suggest you use a fork of this project -- https://github.com/ShayBox/Mon2Cam
